---
# using apiVersion v1
apiVersion: v1
# specify type of Kubernetes resource
kind: Secret
metadata:
  # set secret name on metadata with mongo-secret value
  name: mongo-secret
# set secret type to Opaque
type: Opaque
# set secret data with MONGO_ROOT_USERNAME and MONGO_ROOT_PASSWORD key value
stringData:
  MONGO_ROOT_USERNAME: admin
data:
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA== # encoded mongodb password
  
