---
# using apiVersion v1
apiVersion: v1
kind: Service
metadata:
  # set service name on metadata with karsajobs-service value
  name: karsajobs-service
  labels:
    # set label with app karsajobs
    app: karsajobs
spec:
  # set service type to NodePort
  type: NodePort
  # set selector from metadata for service
  selector:
    app: karsajobs
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    # set NodePort to 30006
    nodePort: 30006